// Generated by ts-to-zod
import { z } from "zod";

export const tradeSchema = z.object({
  size: z.number(),
  price: z.number(),
  tradeType: z.string(),
  assetType: z.string(),
  assetTicker: z.string(),
  issuerName: z.string(),
  issuerTicker: z.string(),
  polFirstName: z.string(),
  polLastName: z.string(),
  polChamber: z.string(),
  reportingGap: z.number(),
});

const cTTradePagingSchema = z.object({
  page: z.number(),
  size: z.number(),
  totalItems: z.number(),
  totalPages: z.number(),
});

const cTAssetSchema = z.object({
  assetType: z.string(),
  assetTicker: z.string(),
});

const cTIssuerSchema = z.object({
  country: z.string(),
  issuerName: z.string(),
  issuerTicker: z.string(),
});

const cTPoliticianSchema = z.object({
  chamber: z.string(),
  firstName: z.string(),
  gender: z.string(),
  lastName: z.string(),
  party: z.string(),
});

const cTTradeSchema = z.object({
  _txId: z.number(),
  _politicianId: z.string(),
  _assetId: z.number(),
  _issuerId: z.number(),
  txDate: z.string(),
  txType: z.string(),
  txTypeExtended: z.any(),
  chamber: z.string(),
  price: z.number(),
  size: z.number(),
  value: z.number(),
  filingURL: z.string(),
  reportingGap: z.number(),
  committees: z.array(z.string()),
  asset: cTAssetSchema,
  issuer: cTIssuerSchema,
  politician: cTPoliticianSchema,
});

const cTTradeMetaSchema = z.object({
  paging: cTTradePagingSchema,
});

const cTTradeDataSchema = z.object({
  data: z.array(cTTradeSchema),
  meta: cTTradeMetaSchema,
});
